/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppEmployeesRouteImport } from './routes/_app/employees'
import { Route as AppFilesRouteImport } from './routes/_app/files'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppMyWorkRouteImport } from './routes/_app/my-work'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppTeamsRouteImport } from './routes/_app/teams'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app/employees.index'
import { Route as AppEmployeesEmployeeIdRouteImport } from './routes/_app/employees.$employeeId'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects.$projectId'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks.index'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks.$taskId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppMyWorkRoute = AppMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppEmployeesEmployeeIdRoute = AppEmployeesEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppTasksRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/chat': typeof AppChatRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/files': typeof AppFilesRoute
  '/inbox': typeof AppInboxRoute
  '/my-work': typeof AppMyWorkRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/teams': typeof AppTeamsRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/employees/': typeof AppEmployeesIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/chat': typeof AppChatRoute
  '/files': typeof AppFilesRoute
  '/inbox': typeof AppInboxRoute
  '/my-work': typeof AppMyWorkRoute
  '/settings': typeof AppSettingsRoute
  '/teams': typeof AppTeamsRoute
  '/': typeof AppIndexRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/employees': typeof AppEmployeesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/employees': typeof AppEmployeesRouteWithChildren
  '/_app/files': typeof AppFilesRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/my-work': typeof AppMyWorkRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/_app/teams': typeof AppTeamsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/ai'
    | '/analytics'
    | '/calendar'
    | '/chat'
    | '/employees'
    | '/files'
    | '/inbox'
    | '/my-work'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/teams'
    | '/employees/$employeeId'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/api/auth/$'
    | '/employees/'
    | '/projects/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/ai'
    | '/analytics'
    | '/calendar'
    | '/chat'
    | '/files'
    | '/inbox'
    | '/my-work'
    | '/settings'
    | '/teams'
    | '/'
    | '/employees/$employeeId'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/api/auth/$'
    | '/employees'
    | '/projects'
    | '/tasks'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/ai'
    | '/_app/analytics'
    | '/_app/calendar'
    | '/_app/chat'
    | '/_app/employees'
    | '/_app/files'
    | '/_app/inbox'
    | '/_app/my-work'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/teams'
    | '/_app/'
    | '/_app/employees/$employeeId'
    | '/_app/projects/$projectId'
    | '/_app/tasks/$taskId'
    | '/api/auth/$'
    | '/_app/employees/'
    | '/_app/projects/'
    | '/_app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-work': {
      id: '/_app/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof AppMyWorkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/employees/$employeeId': {
      id: '/_app/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AppEmployeesEmployeeIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppEmployeesRouteChildren {
  AppEmployeesEmployeeIdRoute: typeof AppEmployeesEmployeeIdRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesEmployeeIdRoute: AppEmployeesEmployeeIdRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppTasksRouteChildren {
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChatRoute: typeof AppChatRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppFilesRoute: typeof AppFilesRoute
  AppInboxRoute: typeof AppInboxRoute
  AppMyWorkRoute: typeof AppMyWorkRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppTeamsRoute: typeof AppTeamsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChatRoute: AppChatRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppFilesRoute: AppFilesRoute,
  AppInboxRoute: AppInboxRoute,
  AppMyWorkRoute: AppMyWorkRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppTeamsRoute: AppTeamsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
